# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93265da2656d528ac0d140c43b8e93a480ca4e4ca3c8dd6dc90b004a772b25a34f7a95ce1cb3e01fc51a91dc9b6dc34ebd0fa07aa0ad6b67a2ce3c0cd5f7b634

test:
  secret_key_base: 09fd58d424039ac46910d34d215ed17aea900d9899bdb326358b35159257f564beef2394257d99688d9fac1602b3ac6eba8f082cc59b291e506ab2011987aa85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
